[build]
  functions = "functions"
  publish = "public"
  command = "echo build skipped"

# CORS for the function responses
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "*"
