[build]
  functions = "functions"
  publish = "public"
  command = "echo build skipped"

[[headers]]
  for = "/.netlify/functions/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
            Access-Control-Allow-Methods = "GET, O
